### ISSUE TITLE
background argument is ignored

### ISSUE THREAD

**Issue by jdekanter** [campbio/celda#355] opened 2022-01-13 15:07 UTC
Hi Joshua!

Thanks for writing this great tool!
I'm running decontX on a dataset of FACS sorted 384 well plates.
In each plate,  16 wells were left empty as a control (to estimate the background levels of RNA), which I now use for decontX as background.
My problem is that it seems that the "background" argument is ignored.
I ran plate-per-plate, and each time provided the empty wells as a Matrix in the "background" argument (see below).
However, it then still runs UMAP, and clustering. 
Indeed, if I repeat the code, but leave the "background" argument empty, I get the exact same values in the "decontXcounts" output slot. 
Do you have any idea what might be happening?

The code I use is:

```
meta # this is just a meta_data data.frame, containing plate and empty/full well information
data # this is a sparse Matrix with all data combined.

filtered_list = meta$plate_id %>% 
  unique %>% # run per plate
  sort %>%
  lapply(function(plate) {
    meta_plate = meta[meta$plate_id == plate, ]
    empty = meta_plate %>% filter(factor == "empty") %>% pull('well') # none overlap with "full", all are colnames of "data"
    full = meta_plate %>% filter(factor != "empty") %>% pull('well')
    corrected = decontX(x = data[  ,full], background = data[  ,empty])
  })
```
Output is: 
```
--------------------------------------------------
Starting DecontX
--------------------------------------------------
Thu Jan 13 16:06:03 2022 .. Analyzing all cells
Thu Jan 13 16:06:03 2022 .... Generating UMAP and estimating cell types
Thu Jan 13 16:06:09 2022 .... Estimating contamination
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 10 | converge: 0.02943
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 20 | converge: 0.008695
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 30 | converge: 0.004772
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 40 | converge: 0.003511
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 50 | converge: 0.003405
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 60 | converge: 0.001892
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 70 | converge: 0.001466
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 80 | converge: 0.001035
Thu Jan 13 16:06:09 2022 ...... Completed iteration: 84 | converge: 0.0009911
Thu Jan 13 16:06:09 2022 .. Calculating final decontaminated matrix
``` 
etc

This gives the exact same result as:

```filtered_list = meta$plate_id %>% 
  unique %>% # run per plate
  sort %>%
  lapply(function(plate) {
    meta_plate = meta[meta$plate_id == plate, ]
    empty = meta_plate %>% filter(factor == "empty") %>% pull('well')
    full = meta_plate %>% filter(factor != "empty") %>% pull('well')
    corrected = decontX(x = data[  ,full])
  })```

**Comment by joshua-d-campbell** [comment] 2022-01-14 14:57
Thanks @jdekanter, all of the input looks okay, so I'm not sure what is going on exactly. We may need to look into it more carefully and see if we can recapitulate the issue. If we can't reproduce it on our end, would it be possible for you to send us an example matrix that produces the issue? In the meantime, running decontX without the background matrix may still help with some decontamination for your data to some degree. If certain cell populations were excluded when your plates were being sorted, then the markers from those population may still show up.

**Comment by yuan-yin-truly** [comment] 2022-01-15 00:49
Hi @jdekanter, this is a bug. 

A temporary solution is to convert your matrices into SingleCellExperiment objects before feeding them to decontX:

`data_full_sce <- SingleCellExperiment(assays = list(counts = data_full))`
`data_empty_sce <- SingleCellExperiment(assays = list(counts = data_empty))`
`data_full_sce <- decontX(x = data_full_sce, background = data_empty_sce)`

Hi @joshua-d-campbell, I will create a separate pull request after fixing this. Please feel free to assign it to me.

**Comment by joshua-d-campbell** [comment] 2022-01-16 18:57
This issue has been fixed in the development branch. The development branch can be installed via devtools:

```
library(devtools)
install_github("campbio/celda@devel")
```

You can also use the SingleCellExperiment object to get around this as @yuan-yin-truly mentioned. I'm going to close this issue for now but let us know if you have other problems with it.

**Closed by joshua-d-campbell** 2022-01-16 18:57 UTC
